identidock:
        build: .
        ports:
                - "5000:5000"
        environment:
                ENV: DEV
        volumes:
                - d:/python/identidock/app:/app
        links:
                - dnmonster
                

dnmonster:
        image: amouat/dnmonster:latest